#depolyment , service 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-helm
  labels:
    project: expense
    tire: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tire: db
  template:
    metadata:
      labels:
        project: expense
        tire: db
    spec:
      containers:
      - name: mysql
        image:  promptforai/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    project: expense
    tire: db
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: {{ .Values.Service.port }}   # service port, #place holders
    targetPort: 3306  # container port 



